### ISSUE TITLE
Running with a Jupyter Notebook

### ISSUE THREAD

**Issue by rgerkin** [russelljjarvis/PyNeuron-Toolbox#2]
@russelljjarvis 
So I've started using this to launch the Jupyter Notebook, using:
`docker run -d -p 8888:8888 -v /path/to/my/Dropbox:/home/docker/Dropbox russelljarvis/pyneuron-toolbox:latest sh -c "jupyter-notebook --ip=0.0.0.0 --no-browser"`which I can then access from my web browser outside of Docker to read/write/execute notebooks that are in my Dropbox.

The only problem is that I still need to add a few more python libraries, e.g. matplotlib.  Do you think it makes sense to 1) edit this Docker image (as described in the Dockerfile here), or 2) to start a new one based on this, or 3) to create an entirely new one that has the minimum necessary to run the SciUnit/NeuronUnit examples but doesn't necessarily have fancy things like parallel Neuron?

**Comment by rgerkin** [comment]
For 3), I might start with something like the scipy-stack [here](https://github.com/jupyter/docker-stacks), and then add stuff to it.

**Comment by russelljjarvis** [comment]
I am also unsure about what would be the best to reduce complexity, out of 1 make a big distribution that has everything or many or most things, or 2. Have some smaller minimal distributions that are less bloated. When I created this docker image I was not sure whether or not incrementally build up from a more minimal image, by starting with a statement like:

FROM minimal_jupyter_nunit

The only problem with this approach as I see it is maintainability. It means someone has to be responsible for maintaining the build processes of two files instead of just one file. 

It probably wouldn't hurt multiple minimal builds that achieve substantially different environments, as long as it does not take too much work to maintain, as I was thinking that when new versions of neuronunit, NEURON, NeuroML come out it will be someones job to update lines of the build file appropriately to mirror those changes. 

Also if something breaks in the build process I thought it might be more convenient (to an outsider) to have it all in one file.  On the other hand it might help to isolate breaks in the build for developers if builds are distributed over two or more files. It would be great to know what the docker community thinks about this issue. I don't think it would hurt to make a different minimal build, and to use trial and error to find out what is the most maintainable and less complex build process.

I did not know about the docker scipy-stack, it looks awesome.

Also you have reminded me of a different issue about should there be persistent memory inside the image, or should parts of the host file system (or even DropBox as a remote files system) be mounted instead. It looks like your usage pattern is to mount DropBox as if it is on the host system, and I expect I will do so too, so probably persistent memory is completely unnecessary. If we assume that neuronunit developers will use the build by mounting some part of the host file system, then I can omit vim and emacs from the build too.

It would be easy to build Python+NEURON on top of the sci-py stack. I think you just need the following note the parallel compilation flag 'with-paranrn=/usr/bin/mpiexec' has been ommitted.

WORKDIR /home/docker/neuron
#Fetch NEURON source files, extract them, delete .tar.gz file.
RUN \
  sudo wget http://www.neuron.yale.edu/ftp/neuron/versions/v7.4/nrn-7.4.tar.gz && \
  sudo tar -xzf nrn-7.4.tar.gz && \
  sudo rm nrn-7.4.tar.gz 

WORKDIR /home/docker/neuron/nrn-7.4
RUN sudo ./configure --prefix=`pwd` --without-iv --with-nrnpython=/opt/conda/bin/python
RUN sudo make all && \
   sudo make install

#Create python bindings for NEURON
WORKDIR src/nrnpython
RUN sudo /opt/conda/bin/python setup.py install
ENV PATH $HOME/neuron/nrn-7.4/x86_64/bin:$PATH

**Comment by rgerkin** [comment]
We are past this issue.
